columns:
    # optional columns to add. The default one is always: `index` or GC#.
    # to add a column, add it from the ``available_columns`` section.
    - type
    - gen
    - pause (ms)
    - reason
    - gen0 size at end of this GC
    - genlargeobj size at end of this GC
    - finalize promoted for GC

available_columns:
    # all columns available to be displayed.
    - gen                                 # The Generation.
    - type                                # Type of GC.
    - pause (ms)                          # The amount of time that execution in managed code is blocked because the GC needs exclusive use to the heap. For background GCs this is small.
    - reason                              # Reason for GC.
    - suspension time (ms)                # The time in milliseconds that it took to suspend all threads to start this GC. For background GCs, we pause multiple times, so this value may be higher than for foreground GCs.
    - pause time % since last GC          # The amount of time that execution in managed code is blocked because the GC needs exclusive use to the heap. For background GCs this is small
    - percent time in GC                  # Since the last GC, GC pause time expressed as a percentage of total process time. For background GC, this includes the pause time for foreground GCs that occur during the background GC.
    - amount allocated in gen 0           # Amount allocated since the last GC occurred.
    - gen0 allocation rate                # The average allocation rate since the last GC.
    - peak                                # The peak size of the GC during GC.
    - size at end of this GC              # The size after GC (includes fragmentation).
    - ratio of peak/after                 # Peak / After.
    - memory this gc promoted             # Memory this GC promoted.

    # Gen0
    - gen0 size at end of this GC         # Size of gen0 at the end of this GC.
    - gen0 survival rate                  # The % of objects in Gen0 that survived this GC.
    - gen0 frag ratio                     # The % of free space on gen0.

    # Gen1
    - gen1 size at end of this GC         # Size of gen1 at the end of this GC.
    - gen1 survival rate                  # The % of objects in Gen1 that survived this GC. Only available if we are doing a gen1 GC.
    - gen1 frag ratio                     # The % of free space on Gen1 that is betweeen live objects.

    # Gen 2
    - gen2 size at end of this GC         # Size of Gen2 in MB at the end of this GC.
    - gen2 survival rate                  # The % of objects in Gen2 that survived this GC. Only available if we are doing a gen2 GC.
    - gen2 frag ratio                     # The % of free space on gen2.

    # LOH
    - genlargeobj size at end of this GC  # Size of Large object heap (LOH) in MB at the end of this GC.
    - genlargeobj survival rate           # The % of objects in the large object heap (LOH) that survived the GC. Only available if we are doing a gen2 GC.
    - genlargeobj frag ratio              # The % of free space that is between live objects on the large object heap (LOH).

    # Finalized and Pinned
    - finalize promoted for GC            # The number of MB of objects that have finalizers (destructors) that survived this GC.
    - no. of pinned objects for GC        # Number of pinned objects this GC promoted.