columns:
    # optional columns to add. The default one is always: `index` or GC#.
    - type
    - gen
    - pause (ms)

#TODO: Add once implemented:
# stats_mode:
# could be manual which means it'll only show if you press s, or timer and you can specify the interval
#    timer_in_seconds: 5

available_columns:
    # all columns available - could be many here since TraceGC exposes lots of stuff
    - gen        # Number of Generation
    - type       # Type of GC
    - pause (ms) # GC Pause Time in MSec  
    - reason     # GC Reason